### ISSUE TITLE
Removing Containers with script in readme not accounting for networks

### ISSUE THREAD

**Issue by chasecbw** [bryanlittlefield/TUGBOAT#27]
While it is handy to have the stop/remove all containers snippets in the readme markdown, this doesn't account for disconnecting/removing the networks that are established where `docker-compose down` does.

I suggest adding in a snippet to close the networks as well. `docker network rm $(docker network ls -a -q)' <~~not tested

Either that or adding a snippet that properly removes all containers as `docker-compose down` would

**Comment by bryanlittlefield** [comment]
Updated the Wiki with a page detailing a few methods to achieve this. Using docker network prune is recommended in this scenario.

See [TUGBOAT - Wiki - OCKER NETWORKS](https://github.com/bryanlittlefield/TUGBOAT/wiki/DOCKER-NETWORKS)
