### ISSUE TITLE
The GD library is not successfully installing FreeType support. 

### ISSUE THREAD

**Issue by chasecbw** [bryanlittlefield/TUGBOAT#65]
The GD library is not successfully installing FreeType support. 

Line 71 of https://github.com/bryanlittlefield/tugboat-php/blob/master/Dockerfile seems like it should be correctly installing freetype, but when running phpinfo(); The GD library is not displaying freetype support. It is also creating errors on Magento 2 whenever the CAPTCHA is being loaded.

Lastly, the directory path on the `--with-freetype-dir=` flag on the `docker-php-ext-configure gd` cmd on line 71 looks to be incomplete.

You might consider updating that line to `docker-php-ext-configure gd --with-freetype-dir=/usr/include/freetype2/ --with-jpeg-dir=/usr/include/` and testing

Thanks!

**Comment by insanityfarm** [comment]
I think this is the same bug: https://github.com/docker-library/php/issues/608
